Feature/X25519
cubbit/enigma pull request #19
Opened 2020-10-16 14:25 UTC by lurenzsgp

2020-10-19 09:09 UTC, marmos91 requested changes

2020-10-19 09:09 UTC, marmos91 commented on src/node/modules/X25519.ts
> +        return this._aes.decrypt(cipher)
```suggestion
        if(!this._aes)
            throw new Error('Init method must be called first');
            
        return this._aes.decrypt(cipher)
```

2020-10-19 09:29 UTC, marmos91 approved these changes
LGTM

2020-10-22 07:51 UTC, marmos91 approved these changes

2020-10-28 02:06 UTC, alessiopcc approved these changes

2020-10-28 02:07 UTC, merged